### ISSUE TITLE
cyclic_buffer usage example after data read

### ISSUE THREAD

**Issue by salieri11** [mabrarov/asio_samples#178]
Hi , great repo! I wonder if you have any example of using your cyclic_buffer's data after it has been filled by async_read_some.
Basically, in my scenario, i can have a lot of back to back messages on the socket, each of them in the form of 4 bytes header + payload. Cyclic buffer allows me to read as much as I can from the socket, and then to parse these bytes. And if I don;t have complete message at the end - I will issue next read_some operation to the end of the buffer.
But I don't see how I can consume the received data. I can use .data() , but how can I access underlying char* ?

**Comment by mabrarov** [comment]
Hi,

Can [`boost::asio::buffers_iterator`](https://www.boost.org/doc/libs/1_75_0/doc/html/boost_asio/reference/buffers_iterator.html) help you to iterate over the bytes of const buffer sequence returned by `ma::cyclic_buffer::data`?

Like:

```cpp
TEST(complex_test, looping_filled_space)
{
  typedef ma::cyclic_buffer::const_buffers_type const_buffers_type;
  typedef ma::cyclic_buffer::mutable_buffers_type mutable_buffers_type;
  typedef boost::asio::buffers_iterator<const_buffers_type> const_buffers_iterator;
  typedef boost::asio::buffers_iterator<mutable_buffers_type> mutable_buffers_iterator;
  ma::cyclic_buffer buffer(16);
  {
    char num = 0;
    mutable_buffers_type nonfilled = buffer.prepared();
    for (mutable_buffers_iterator i = mutable_buffers_iterator::begin(nonfilled),
        end = mutable_buffers_iterator::end(nonfilled); i != end; ++i)
    {
      *i = num++;
    }
  }
  buffer.consume(buffer.size());
  {
    char num = 0;
    const_buffers_type filled = buffer.data();
    for (const_buffers_iterator i = const_buffers_iterator::begin(filled),
        end = const_buffers_iterator::end(filled); i != end; ++i)
    {
      ASSERT_EQ(static_cast<int>(num++), static_cast<int>(*i));
    }
  }
}
```

**Comment by salieri11** [comment]
I see. Makes sense. I will give it a try. Thanks!

**Comment by mabrarov** [comment]
Added test which demonstrates looping over filled and nonfilled parts of `ma::cyclic_buffer` in c625dba15bb7a8ac9096757ed19d201228e6132b.

**Comment by mabrarov** [comment]
Refer to Boost.Asio documentation: [Overview. Buffers. Bytewise Traversal of Buffer Sequences](https://www.boost.org/doc/libs/1_75_0/doc/html/boost_asio/overview/core/buffers.html#boost_asio.overview.core.buffers.bytewise_traversal_of_buffer_sequences).
