### ISSUE TITLE
Failure to compile. Must statically link to boost.

### ISSUE THREAD

**Issue by davidgwright** [mabrarov/asio_samples#48]
Great project by the way.

I am using VS 2015 update 2.

Is it mandatory to have -D Boost_USE_STATIC_LIBS=ON, it was the only way I could get it to compile?

My cmake batch file : 

cmake -D BOOST_INCLUDEDIR=C:\Development\ThirdParty\BOOST\boost_1_60_0 -D BOOST_LIBRARYDIR=C:\Development\ThirdParty\BOOST\boost_1_60_0\lib64-msvc-14.0 -D Boost_NO_SYSTEM_PATHS=ON -D Boost_USE_STATIC_LIBS=ON -D Qt5Widgets_DIR=C:\Development\ThirdParty\QT\5.6\msvc2015_64/lib/cmake/Qt5Widgets -G "Visual Studio 14 2015 Win64" .

**Comment by mabrarov** [comment]
It is recommended to explicitly use `Boost_USE_STATIC_LIBS=ON` in case you want to link against static version of Boost. It is required to link against static Boost libraries in case you want to use static C/C++ runtime (this requirement is specific for Windows platform, I guess).
I appreciate if you could share output (console, MSVS) in case you have errors (cmake project generation errors or build errors, etc).

**Comment by mabrarov** [comment]
I'm using VS 2015 update 2 with static version Boost C++ Libraries also, BTW.

**Comment by mabrarov** [comment]
It seems that `-D Boost_USE_STATIC_LIBS=OFF` is not enough to make Boost autolinking select dynamic libraries instead static (it seems that Boost autolinking almost always selects static libraries).

**Comment by mabrarov** [comment]
Fixed cmake project to turn off Boost autolinking in case `-D Boost_USE_STATIC_LIBS=ON` is not used (by default  `Boost_USE_STATIC_LIBS` is `OFF` according to [FindBoost documentation](https://cmake.org/cmake/help/v3.5/module/FindBoost.html)) in pull request #51.

**Comment by mabrarov** [comment]
Tested with Boost 1.60 and MSVS 2015 update 2.
